FROM public.ecr.aws/lambda/nodejs:22-arm64
WORKDIR ${LAMBDA_TASK_ROOT}

COPY package*.json ./
COPY prisma ./prisma

RUN npm ci --omit=dev && npm run prisma:generate
COPY . .
RUN npm run build

CMD ["dist/index.handler"]
